global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'docker-registry'
    static_configs:
      - targets: ['registry:443']
    tls_config:
      insecure_skip_verify: true
    scheme: https
    metrics_path: /metrics
